name: Keep Render Warm
on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch: {}
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - run: curl -sS -m 10 https://devspace.madhusudan.space || true
